package com.project.QR.exception;

import lombok.Getter;

public enum ExceptionCode {
  MEMBER_NOT_FOUND(404, "MEMBER NOT FOUND"),
  MEMBER_ALREADY_EXISTS(409, "MEMBER ALREADY EXISTS"),
  FIELD_ERROR(400, "FIELD ERROR"),
  CONSTRAINT_VIOLATION_ERROR(400, "CONSTRAINT VIOLATION ERROR"),
  NOT_IMPLEMENTATION(501, "Not Implementation"),
  INVALID_MEMBER_STATUS(400, "INVALID MEMBER STATUS"),
  MEMBER_INFO_INCORRECT(404, "LOGIN INFO IS INCORRECT"),
  FILE_UPLOAD_FAIL(500, "FILE_UPLOAD_FAIL"),
  FOLDER_MAKE_FAIL(500, "FOLDER_MAKE_FAIL"),
  TOKEN_IS_INVALID(401, "TOKEN IS INVALID"),
  REFRESH_TOKEN_IS_EXPIRED(403, "REFRESH TOKEN IS EXPIRED"),
  VALIDATION_CODE_INCORRECT(404, "VALIDATION CODE IS INCORRECT"),
  EMAIL_VALIDATION_NEED(403, "EMAIL VALIDATION IS NEED"),
  ROLE_IS_NOT_EXISTS(403, "Role is not exists"),
  QR_CODE_NOT_FOUND(404, "QR CODE IS NOT FOUND"),
  RESERVATION_ALREADY_EXISTS(409, "RESERVATION IS ALREADY EXISTS"),
  RESERVATION_NOT_FOUND(404, "RESERVATION IS NOT FOUND"),
  INVALID_INFO(403, "INVALID INFO"),
  BUSINESS_NOT_FOUND(404, "BUSINESS IS NOT FOUND"),
  MENU_NOT_FOUND(404, "MENU IS NOT FOUND"),
  MENU_ALREADY_EXISTS(409, "MENU ALREADY EXISTS"),
  REVIEW_NOT_FOUND(404, "REVIEW IS NOT FOUND"),
  KEEP_ALREADY_EXISTS(409, "KEEP ALREADY EXISTS"),
  KEEP_NOT_FOUND(404, "KEEP IS NOT FOUND"),
  FILE_EXTENSION_INVALID(403, "FILE EXTENSION IS INVALID");

  @Getter
  private int status;

  @Getter
  private String message;

  ExceptionCode(int code, String message) {
    this.status = code;
    this.message = message;
  }
}
